[rospy.client][INFO] 2022-02-23 12:29:25,305: init_node, name[/Robotiq2FGripperRtuNode], pid[2076]
[xmlrpc][INFO] 2022-02-23 12:29:25,306: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-02-23 12:29:25,306: Started XML-RPC server [http://FM00351-u:44155/]
[rospy.init][INFO] 2022-02-23 12:29:25,307: ROS Slave URI: [http://FM00351-u:44155/]
[rospy.impl.masterslave][INFO] 2022-02-23 12:29:25,307: _ready: http://FM00351-u:44155/
[rospy.registration][INFO] 2022-02-23 12:29:25,308: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-02-23 12:29:25,308: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-02-23 12:29:25,407: registered with master
[rospy.rosout][INFO] 2022-02-23 12:29:25,407: initializing /rosout core topic
[rospy.rosout][INFO] 2022-02-23 12:29:25,409: connected to core topic /rosout
[rospy.simtime][INFO] 2022-02-23 12:29:25,409: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-02-23 12:29:25,647: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-02-23 12:29:29,593: topic[/Robotiq2FGripperRobotOutput] adding connection to [http://FM00351-u:37223/], count 0
[rospy.internal][INFO] 2022-02-23 12:29:32,432: topic[/Robotiq2FGripperRobotInput] adding connection to [/Robotiq2FGripperSlipController_2100_1645619369296], count 0
[rospy.internal][WARNING] 2022-02-23 12:29:55,802: Unknown error initiating TCP/IP socket to FM00351-u:36331 (http://FM00351-u:37223/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2022-02-23 12:29:55,802: topic[/Robotiq2FGripperRobotOutput] removing connection to http://FM00351-u:37223/
[rospy.internal][INFO] 2022-02-23 12:29:55,859: topic[/Robotiq2FGripperRobotInput] removing connection to /Robotiq2FGripperSlipController_2100_1645619369296
[rospy.internal][INFO] 2022-02-23 12:30:23,595: topic[/Robotiq2FGripperRobotOutput] adding connection to [http://FM00351-u:34255/], count 0
[rospy.internal][INFO] 2022-02-23 12:30:25,062: topic[/Robotiq2FGripperRobotInput] adding connection to [/Robotiq2FGripperSlipController_2121_1645619423329], count 0
[rospy.internal][ERROR] 2022-02-23 12:39:11,347: Unable to initiate TCP/IP socket to FM00351-u:44415 (http://FM00351-u:34255/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2022-02-23 12:39:11,378: topic[/Robotiq2FGripperRobotInput] removing connection to /Robotiq2FGripperSlipController_2121_1645619423329
[rospy.internal][WARNING] 2022-02-23 12:39:12,349: Unknown error initiating TCP/IP socket to FM00351-u:44415 (http://FM00351-u:34255/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-02-23 12:39:12,349: topic[/Robotiq2FGripperRobotOutput] removing connection to http://FM00351-u:34255/
[rosout][WARNING] 2022-02-23 12:39:12,349: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2022-02-23 12:39:12,350: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 325, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2022-02-23 12:39:15,047: topic[/Robotiq2FGripperRobotOutput] adding connection to [http://FM00351-u:42953/], count 0
[rospy.internal][INFO] 2022-02-23 12:39:17,323: topic[/Robotiq2FGripperRobotInput] adding connection to [/Robotiq2FGripperSlipController_2139_1645619954838], count 0
[rospy.internal][ERROR] 2022-02-23 12:41:06,238: Unable to initiate TCP/IP socket to FM00351-u:40197 (http://FM00351-u:42953/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2022-02-23 12:41:06,295: topic[/Robotiq2FGripperRobotInput] removing connection to /Robotiq2FGripperSlipController_2139_1645619954838
[rospy.internal][WARNING] 2022-02-23 12:41:07,239: Unknown error initiating TCP/IP socket to FM00351-u:40197 (http://FM00351-u:42953/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-02-23 12:41:07,240: topic[/Robotiq2FGripperRobotOutput] removing connection to http://FM00351-u:42953/
[rospy.internal][INFO] 2022-02-23 12:41:10,739: topic[/Robotiq2FGripperRobotOutput] adding connection to [http://FM00351-u:33871/], count 0
[rospy.internal][WARNING] 2022-02-23 12:41:23,079: Unknown error initiating TCP/IP socket to FM00351-u:41461 (http://FM00351-u:33871/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2022-02-23 12:41:23,080: topic[/Robotiq2FGripperRobotOutput] removing connection to http://FM00351-u:33871/
[rospy.internal][INFO] 2022-02-23 12:41:26,864: topic[/Robotiq2FGripperRobotOutput] adding connection to [http://FM00351-u:33075/], count 0
[rospy.internal][INFO] 2022-02-23 12:41:28,372: topic[/Robotiq2FGripperRobotInput] adding connection to [/Robotiq2FGripperSlipController_2170_1645620086638], count 0
[rospy.internal][ERROR] 2022-02-23 12:41:41,849: Unable to initiate TCP/IP socket to FM00351-u:35371 (http://FM00351-u:33075/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2022-02-23 12:41:41,874: topic[/Robotiq2FGripperRobotInput] removing connection to /Robotiq2FGripperSlipController_2170_1645620086638
[rospy.internal][WARNING] 2022-02-23 12:41:42,850: Unknown error initiating TCP/IP socket to FM00351-u:35371 (http://FM00351-u:33075/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-02-23 12:41:42,851: topic[/Robotiq2FGripperRobotOutput] removing connection to http://FM00351-u:33075/
[rospy.internal][INFO] 2022-02-23 12:41:43,692: topic[/Robotiq2FGripperRobotOutput] adding connection to [http://FM00351-u:36757/], count 0
[rospy.internal][INFO] 2022-02-23 12:41:45,677: topic[/Robotiq2FGripperRobotInput] adding connection to [/Robotiq2FGripperSlipController_2187_1645620103493], count 0
[rospy.internal][WARNING] 2022-02-23 12:42:00,972: Unknown error initiating TCP/IP socket to FM00351-u:41255 (http://FM00351-u:36757/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2022-02-23 12:42:00,972: topic[/Robotiq2FGripperRobotOutput] removing connection to http://FM00351-u:36757/
[rospy.internal][INFO] 2022-02-23 12:42:01,023: topic[/Robotiq2FGripperRobotInput] removing connection to /Robotiq2FGripperSlipController_2187_1645620103493
[rospy.internal][INFO] 2022-02-23 12:43:10,904: topic[/Robotiq2FGripperRobotOutput] adding connection to [http://FM00351-u:37359/], count 0
[rospy.internal][INFO] 2022-02-23 12:43:16,616: topic[/Robotiq2FGripperRobotInput] adding connection to [/Robotiq2FGripperSlipController_2203_1645620190675], count 0
[rospy.internal][WARNING] 2022-02-23 12:48:20,288: Unknown error initiating TCP/IP socket to FM00351-u:39675 (http://FM00351-u:37359/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2022-02-23 12:48:20,288: topic[/Robotiq2FGripperRobotOutput] removing connection to http://FM00351-u:37359/
[rospy.internal][INFO] 2022-02-23 12:48:20,343: topic[/Robotiq2FGripperRobotInput] removing connection to /Robotiq2FGripperSlipController_2203_1645620190675
[rospy.internal][INFO] 2022-02-23 12:48:22,541: topic[/Robotiq2FGripperRobotOutput] adding connection to [http://FM00351-u:36729/], count 0
[rospy.internal][INFO] 2022-02-23 12:48:25,269: topic[/Robotiq2FGripperRobotInput] adding connection to [/Robotiq2FGripperSlipController_2220_1645620502281], count 0
[rospy.core][INFO] 2022-02-23 13:02:15,902: signal_shutdown [atexit]
[rospy.internal][INFO] 2022-02-23 13:02:15,906: topic[/Robotiq2FGripperRobotInput] removing connection to /Robotiq2FGripperSlipController_2220_1645620502281
[rospy.internal][INFO] 2022-02-23 13:02:15,906: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-02-23 13:02:15,906: topic[/Robotiq2FGripperRobotOutput] removing connection to http://FM00351-u:36729/
[rospy.impl.masterslave][INFO] 2022-02-23 13:02:15,906: atexit
