[rospy.client][INFO] 2022-03-09 09:44:10,191: init_node, name[/Robotiq2FGripperRtuNode], pid[3322]
[xmlrpc][INFO] 2022-03-09 09:44:10,191: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-03-09 09:44:10,191: Started XML-RPC server [http://FM00351-u:36899/]
[rospy.init][INFO] 2022-03-09 09:44:10,191: ROS Slave URI: [http://FM00351-u:36899/]
[rospy.impl.masterslave][INFO] 2022-03-09 09:44:10,191: _ready: http://FM00351-u:36899/
[rospy.registration][INFO] 2022-03-09 09:44:10,192: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-03-09 09:44:10,192: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-03-09 09:44:10,292: registered with master
[rospy.rosout][INFO] 2022-03-09 09:44:10,292: initializing /rosout core topic
[rospy.rosout][INFO] 2022-03-09 09:44:10,293: connected to core topic /rosout
[rospy.simtime][INFO] 2022-03-09 09:44:10,294: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-03-09 09:44:10,603: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-03-09 09:58:43,218: topic[/Robotiq2FGripperRobotOutput] adding connection to [http://FM00351-u:46013/], count 0
[rospy.internal][INFO] 2022-03-09 09:58:43,218: topic[/Robotiq2FGripperRobotOutput] adding connection to [http://FM00351-u:33087/], count 0
[rospy.internal][WARNING] 2022-03-09 10:08:58,084: Unknown error initiating TCP/IP socket to FM00351-u:36769 (http://FM00351-u:33087/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2022-03-09 10:08:58,085: topic[/Robotiq2FGripperRobotOutput] removing connection to http://FM00351-u:33087/
[rospy.core][INFO] 2022-03-09 10:09:05,686: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-03-09 10:09:05,687: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-03-09 10:09:05,687: topic[/Robotiq2FGripperRobotOutput] removing connection to http://FM00351-u:46013/
[rospy.internal][WARNING] 2022-03-09 10:09:05,688: Unknown error initiating TCP/IP socket to FM00351-u:44261 (http://FM00351-u:46013/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 563, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.impl.masterslave][INFO] 2022-03-09 10:09:05,688: signal-2
[rospy.core][INFO] 2022-03-09 10:09:05,810: signal_shutdown [atexit]
