[rospy.client][INFO] 2022-03-10 09:54:51,018: init_node, name[/gripper_action_server], pid[500]
[xmlrpc][INFO] 2022-03-10 09:54:51,018: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-03-10 09:54:51,018: Started XML-RPC server [http://FM00351-u:37651/]
[rospy.init][INFO] 2022-03-10 09:54:51,018: ROS Slave URI: [http://FM00351-u:37651/]
[rospy.impl.masterslave][INFO] 2022-03-10 09:54:51,018: _ready: http://FM00351-u:37651/
[rospy.registration][INFO] 2022-03-10 09:54:51,020: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-03-10 09:54:51,020: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-03-10 09:54:51,119: registered with master
[rospy.rosout][INFO] 2022-03-10 09:54:51,119: initializing /rosout core topic
[rospy.rosout][INFO] 2022-03-10 09:54:51,123: connected to core topic /rosout
[rospy.simtime][INFO] 2022-03-10 09:54:51,125: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-03-10 09:54:51,382: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-03-10 09:55:56,044: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:42849/], count 0
[rospy.internal][INFO] 2022-03-10 09:55:56,045: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:42849/], count 0
[rospy.internal][INFO] 2022-03-10 09:55:56,064: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:55:56,065: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:55:56,065: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rosout][INFO] 2022-03-10 09:55:56,077: state: initializing
[rosout][INFO] 2022-03-10 09:55:56,078: controller is started now
[rospy.internal][INFO] 2022-03-10 09:55:56,109: topic[/Robotiq2FGripperRobotInput] adding connection to [http://FM00351-u:44707/], count 0
[rospy.internal][INFO] 2022-03-10 09:55:56,131: topic[/Robotiq2FGripperRobotOutput] adding connection to [/Robotiq2FGripperRtuNode], count 0
[rospy.internal][INFO] 2022-03-10 09:57:17,185: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:57:17,188: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][WARNING] 2022-03-10 09:57:17,188: Unknown error initiating TCP/IP socket to FM00351-u:39451 (http://FM00351-u:42849/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][WARNING] 2022-03-10 09:57:17,188: Unknown error initiating TCP/IP socket to FM00351-u:39451 (http://FM00351-u:42849/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2022-03-10 09:57:17,190: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:57:17,190: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:42849/
[rospy.internal][INFO] 2022-03-10 09:57:17,190: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:42849/
[rospy.internal][INFO] 2022-03-10 09:57:19,743: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:57:19,781: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:57:19,782: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:35639/], count 0
[rospy.internal][INFO] 2022-03-10 09:57:19,796: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:35639/], count 0
[rospy.internal][INFO] 2022-03-10 09:57:19,845: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][WARNING] 2022-03-10 09:57:20,125: Unknown error initiating TCP/IP socket to FM00351-u:35931 (http://FM00351-u:35639/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2022-03-10 09:57:20,138: Unknown error initiating TCP/IP socket to FM00351-u:35931 (http://FM00351-u:35639/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2022-03-10 09:57:20,143: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:35639/
[rospy.internal][INFO] 2022-03-10 09:57:20,152: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:35639/
[rospy.internal][INFO] 2022-03-10 09:57:20,286: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:57:20,288: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:57:20,291: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:57:31,647: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:57:31,656: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:34975/], count 0
[rospy.internal][INFO] 2022-03-10 09:57:31,662: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:57:31,662: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:34975/], count 0
[rospy.internal][INFO] 2022-03-10 09:57:31,679: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][WARNING] 2022-03-10 09:57:31,727: Unknown error initiating TCP/IP socket to FM00351-u:37949 (http://FM00351-u:34975/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2022-03-10 09:57:31,729: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:34975/
[rospy.internal][WARNING] 2022-03-10 09:57:31,729: Unknown error initiating TCP/IP socket to FM00351-u:37949 (http://FM00351-u:34975/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2022-03-10 09:57:31,735: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:34975/
[rospy.internal][INFO] 2022-03-10 09:57:31,946: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:57:32,170: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:57:32,172: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:58:09,465: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:58:09,482: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:35949/], count 0
[rospy.internal][INFO] 2022-03-10 09:58:09,486: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:58:09,500: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:35949/], count 0
[rospy.internal][INFO] 2022-03-10 09:58:09,504: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][WARNING] 2022-03-10 09:58:09,615: Unknown error initiating TCP/IP socket to FM00351-u:45051 (http://FM00351-u:35949/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2022-03-10 09:58:09,625: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:35949/
[rospy.internal][WARNING] 2022-03-10 09:58:09,642: Unknown error initiating TCP/IP socket to FM00351-u:45051 (http://FM00351-u:35949/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-10 09:58:09,698: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:35949/
[rospy.internal][INFO] 2022-03-10 09:58:09,887: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:58:09,983: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:58:09,985: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 10:07:40,185: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 10:07:40,290: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:41089/], count 0
[rospy.internal][INFO] 2022-03-10 10:07:40,336: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:41089/], count 0
[rospy.internal][INFO] 2022-03-10 10:07:40,441: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 10:07:40,728: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][WARNING] 2022-03-10 10:07:41,172: Unknown error initiating TCP/IP socket to FM00351-u:46527 (http://FM00351-u:41089/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rosout][WARNING] 2022-03-10 10:07:41,184: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][INFO] 2022-03-10 10:07:41,315: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:41089/
[rospy.internal][WARNING] 2022-03-10 10:07:41,316: Unknown error initiating TCP/IP socket to FM00351-u:46527 (http://FM00351-u:41089/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2022-03-10 10:07:41,404: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 10:07:41,528: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 10:07:41,541: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:41089/
[rospy.internal][ERROR] 2022-03-10 10:07:41,543: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 325, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2022-03-10 10:07:41,543: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 10:08:28,172: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 10:08:28,328: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:33879/], count 0
[rospy.internal][INFO] 2022-03-10 10:08:28,330: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:33879/], count 0
[rospy.internal][INFO] 2022-03-10 10:08:28,637: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 10:08:28,738: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][WARNING] 2022-03-10 10:08:28,916: Unknown error initiating TCP/IP socket to FM00351-u:46847 (http://FM00351-u:33879/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][WARNING] 2022-03-10 10:08:28,966: Unknown error initiating TCP/IP socket to FM00351-u:46847 (http://FM00351-u:33879/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-10 10:08:29,016: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:33879/
[rospy.internal][INFO] 2022-03-10 10:08:29,309: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:33879/
[rospy.internal][INFO] 2022-03-10 10:08:29,310: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 10:08:29,311: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 10:08:29,328: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.core][INFO] 2022-03-10 10:10:24,827: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-03-10 10:10:24,957: topic[/Robotiq2FGripperRobotOutput] removing connection to /Robotiq2FGripperRtuNode
[rospy.internal][INFO] 2022-03-10 10:10:25,289: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-03-10 10:10:25,290: topic[/Robotiq2FGripperRobotInput] removing connection to http://FM00351-u:44707/
[rospy.impl.masterslave][INFO] 2022-03-10 10:10:25,301: signal-2
[rosout][INFO] 2022-03-10 10:10:25,304: state: inactive
[rospy.core][INFO] 2022-03-10 10:10:25,577: signal_shutdown [atexit]
